apiVersion: apps/v1
kind: Deployment
metadata:
  name: metabase
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metabase
  template:
    metadata:
      labels:
        app: metabase
    spec:
      containers:
        - name: metabase
          image: metabase/metabase
          ports:
            - containerPort: 3000
          env:
            - name: MB_DB_FILE
              value: /metabase-data/metabase.db
          volumeMounts:
            - name: metabase-persistent-storage
              mountPath: /metabase-data
      volumes:
        - name: metabase-persistent-storage
          persistentVolumeClaim:
            claimName: metabase-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: metabase
spec:
  type: NodePort
  ports:
    - port: 3000
      nodePort: 30001
  selector:
    app: metabase
